steps:
  - label: Lint
    command:
      - bundle install
      - bundle exec rubocop
    agents:
      queue: 'chef'

  - label: Rspec
    command:
      - bundle install
      - bundle exec rspec
    agents:
      queue: 'chef'

  - label: Publish
    env:
      REPO_SERVER: gems.sendgrid.net
    branches: 'master'
    command:
      - bundle install
      - bundle exec rake build
      - mkdir -p ci-repo
      - cp pkg/* ci-repo/
      - workflow publish_package_legacy
    agents:
      queue: 'chef'
